[[jlqml]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8acc9fd0c21c642883d705f41d0085243de09d57"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "ca013965c97a203067ded5a6f86eaef4d3c348c5f7d1a0b13e8fcba7bc8337e7"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.1.3+0/jlqml.v0.1.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[jlqml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bccaba00b68a65e09502f3fe400d2e00619e7ba9"
os = "macos"

    [[jlqml.download]]
    sha256 = "6d39e2b66d0e5501e923aa04e29e08a0cff1e72e90059f3f6049d9dd65bf6f79"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.1.3+0/jlqml.v0.1.3.x86_64-apple-darwin14-cxx11.tar.gz"
[[jlqml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17965eeb93f46c6b6b85fc24263db1c659f85f26"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "a44910bd4ff06aeeed3a3792730624437bbb42c9ec9c25c5c8fe06085280b0d4"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.1.3+0/jlqml.v0.1.3.x86_64-linux-gnu-cxx11.tar.gz"
[[jlqml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "998b10d1488e1115e652a32dab1485863cf571a7"
os = "windows"

    [[jlqml.download]]
    sha256 = "abad72039aceba9e0f3d59d3c9a3751f8f8b8772a96e45e47c9293adc2a60643"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.1.3+0/jlqml.v0.1.3.x86_64-w64-mingw32-cxx11.tar.gz"
