[[jlqml]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6f0dc7ad32bb49b41284d540931b2fabde9a569"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "1d733b1d33677290d46c8371cc88b06e8cf11e979f8c0e91c4ec99cdcc0721dc"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.1.1+0/jlqml.v0.1.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[jlqml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3bccd4fd86aefe62a613bb0d6631aa4c852af00a"
os = "macos"

    [[jlqml.download]]
    sha256 = "6ec943d8c170de669f7d8cbbd35af066fdd3f1db9f52c60651878a77f7ca0c5e"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.1.1+0/jlqml.v0.1.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[jlqml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ce11030db53ccbd37d1019e56bb57d64b1783c6"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "8538192222573bb7a96e8a098871dedcf5ba0a5aff4b6b7e4d162fb64baae6eb"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.1.1+0/jlqml.v0.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[jlqml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "377abbcd96ee8070f15ddc8f510490998ada4168"
os = "windows"

    [[jlqml.download]]
    sha256 = "e5e03dfe920fbd2bef993f1ba4ad14172e39a078d26af9436daf15e6eddb03e5"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.1.1+0/jlqml.v0.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
