# Autogenerated wrapper script for jlqml_jll for powerpc64le-linux-gnu-cxx03-julia_version+1.7.0
export libjlqml

using libcxxwrap_julia_jll
using Qt6Declarative_jll
using Qt6Svg_jll
JLLWrappers.@generate_wrapper_header("jlqml")
JLLWrappers.@declare_library_product(libjlqml, "libjlqml.so.0.5.3")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll, Qt6Declarative_jll, Qt6Svg_jll)
    JLLWrappers.@init_library_product(
        libjlqml,
        "lib/libjlqml.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
